/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.diozero.gradleapp;

import org.junit.jupiter.api.Test;

@SuppressWarnings("static-method")
class AppTest {
	@Test
	void appHasAGreeting() {
		App app = new App();
		app.run();
	}
}
